# Generated by Django 6.0 on 2025-12-11 13:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('priority', models.IntegerField(choices=[(1, 'Critical - Never cut'), (2, 'High Priority'), (3, 'Medium Priority'), (4, 'Low Priority'), (5, 'Flexible - Can be reduced first')], default=3)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contract_start_date', models.DateField(blank=True, null=True)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color_code', models.CharField(default='#5e3e2f', help_text='Hex color for charts', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('base_capacity_per_hour', models.DecimalField(decimal_places=2, help_text='Units produced per hour at 100% efficiency', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('efficiency_factor', models.DecimalField(decimal_places=2, default=0.85, help_text='Production efficiency (0-1)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['site__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShiftConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('shifts_per_day', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('hours_per_shift', models.DecimalField(decimal_places=2, max_digits=4)),
                ('days_per_week', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('includes_saturday', models.BooleanField(default=False)),
                ('includes_sunday', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('unit_weight', models.DecimalField(blank=True, decimal_places=3, help_text='Weight in kg per unit', max_digits=8, null=True)),
                ('shelf_life_days', models.IntegerField(blank=True, help_text='Product shelf life in days', null=True)),
                ('is_fresh', models.BooleanField(default=True, help_text='Fresh product (short shelf life)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='simulation.productcategory')),
                ('default_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_products', to='simulation.productionline')),
            ],
            options={
                'ordering': ['category__name', 'code'],
            },
        ),
        migrations.AddField(
            model_name='productionline',
            name='default_shift_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_lines', to='simulation.shiftconfiguration'),
        ),
        migrations.AddField(
            model_name='productionline',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='simulation.site'),
        ),
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('week_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(53)])),
                ('week_start_date', models.DateField()),
                ('forecast_quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('confidence_level', models.DecimalField(blank=True, decimal_places=2, help_text='Forecast confidence (0-1)', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='simulation.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='simulation.product')),
            ],
            options={
                'ordering': ['year', 'week_number', 'client__name', 'product__code'],
                'indexes': [models.Index(fields=['year', 'week_number'], name='simulation__year_c91a2f_idx'), models.Index(fields=['week_start_date'], name='simulation__week_st_b341ac_idx'), models.Index(fields=['client', 'year', 'week_number'], name='simulation__client__1bb328_idx'), models.Index(fields=['product', 'year', 'week_number'], name='simulation__product_c27793_idx')],
                'unique_together': {('client', 'product', 'year', 'week_number')},
            },
        ),
        migrations.CreateModel(
            name='LineProductAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False, help_text='Is this the default line for this product?')),
                ('production_rate_per_hour', models.DecimalField(blank=True, decimal_places=2, help_text='Override production rate for this product on this line', max_digits=10, null=True)),
                ('changeover_time_minutes', models.IntegerField(default=30, help_text='Time to set up line for this product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_assignments', to='simulation.product')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_assignments', to='simulation.productionline')),
            ],
            options={
                'ordering': ['line__site__name', 'line__name', 'product__code'],
                'unique_together': {('line', 'product')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='productionline',
            unique_together={('site', 'code')},
        ),
    ]
