# Generated by Django 6.0 on 2025-12-11 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionline',
            name='custom_hours_shift_1',
            field=models.DecimalField(decimal_places=2, default=8.0, help_text='Hours for shift 1 (0-12)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='productionline',
            name='custom_hours_shift_2',
            field=models.DecimalField(decimal_places=2, default=8.0, help_text='Hours for shift 2 (0-12)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='productionline',
            name='custom_hours_shift_3',
            field=models.DecimalField(decimal_places=2, default=8.0, help_text='Hours for shift 3 (0-12)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='productionline',
            name='custom_hours_shift_4',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Hours for shift 4 (0-12)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='productionline',
            name='custom_include_saturday',
            field=models.BooleanField(default=False, help_text='Include Saturday in production'),
        ),
        migrations.AddField(
            model_name='productionline',
            name='custom_include_sunday',
            field=models.BooleanField(default=False, help_text='Include Sunday in production'),
        ),
        migrations.AddField(
            model_name='productionline',
            name='custom_shifts_per_day',
            field=models.IntegerField(default=3, help_text='Number of shifts per day (1-4)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='productionline',
            name='use_custom_shift',
            field=models.BooleanField(default=False, help_text='Use custom shift values instead of preset configuration'),
        ),
    ]
