# Generated by Django 6.0 on 2025-12-11 13:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0002_productionline_custom_hours_shift_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionline',
            name='custom_hours_shift_1',
        ),
        migrations.RemoveField(
            model_name='productionline',
            name='custom_hours_shift_2',
        ),
        migrations.RemoveField(
            model_name='productionline',
            name='custom_hours_shift_3',
        ),
        migrations.RemoveField(
            model_name='productionline',
            name='custom_hours_shift_4',
        ),
        migrations.RemoveField(
            model_name='productionline',
            name='custom_include_saturday',
        ),
        migrations.RemoveField(
            model_name='productionline',
            name='custom_include_sunday',
        ),
        migrations.RemoveField(
            model_name='productionline',
            name='custom_shifts_per_day',
        ),
        migrations.RemoveField(
            model_name='productionline',
            name='use_custom_shift',
        ),
        migrations.CreateModel(
            name='LineConfigOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='First day of the override period')),
                ('end_date', models.DateField(help_text='Last day of the override period')),
                ('shifts_per_day', models.IntegerField(help_text='Number of shifts per day (1-4)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('hours_per_shift', models.DecimalField(decimal_places=2, help_text='Hours per shift (0-12)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)])),
                ('include_saturday', models.BooleanField(default=False, help_text='Include Saturday in production')),
                ('include_sunday', models.BooleanField(default=False, help_text='Include Sunday in production')),
                ('reason', models.CharField(blank=True, help_text='Reason for override (e.g., Maintenance, Peak Season, Cleaning)', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_overrides', to='simulation.productionline')),
            ],
            options={
                'ordering': ['line', 'start_date'],
                'indexes': [models.Index(fields=['line', 'start_date', 'end_date'], name='simulation__line_id_b6e503_idx')],
            },
        ),
    ]
