# Generated by Django 6.0 on 2026-01-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0003_remove_productionline_custom_hours_shift_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineconfigoverride',
            name='is_recurrent',
            field=models.BooleanField(default=False, help_text='Whether this override repeats annually (e.g., seasonal events)'),
        ),
    ]
