# Generated by Django 6.0 on 2026-01-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0004_add_is_recurrent_to_lineconfigoverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineconfigoverride',
            name='recurrence_weeks',
            field=models.PositiveIntegerField(blank=True, help_text='Number of weeks between recurrences (e.g., 3 = every 3 weeks from start date)', null=True),
        ),
        migrations.AlterField(
            model_name='lineconfigoverride',
            name='is_recurrent',
            field=models.BooleanField(default=False, help_text='Whether this override repeats periodically (e.g., seasonal events)'),
        ),
    ]
