# Generated by Django 6.0 on 2026-01-05 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0005_add_recurrence_weeks_to_lineconfigoverride'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='client',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='contract_end_date',
        ),
        migrations.RemoveField(
            model_name='client',
            name='contract_start_date',
        ),
        migrations.RemoveField(
            model_name='client',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='demandforecast',
            name='actual_quantity',
        ),
        migrations.RemoveField(
            model_name='demandforecast',
            name='confidence_level',
        ),
        migrations.RemoveField(
            model_name='lineproductassignment',
            name='changeover_time_minutes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_fresh',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shelf_life_days',
        ),
        migrations.RemoveField(
            model_name='site',
            name='address',
        ),
    ]
