# Generated by Django 6.0 on 2026-01-05 13:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0006_remove_unused_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(editable=False, max_length=20, unique=True)),
                ('color_code', models.CharField(default='#9b59b6', help_text='Hex color for charts', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lab Category',
                'verbose_name_plural': 'Lab Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LabClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(editable=False, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lab Client',
                'verbose_name_plural': 'Lab Clients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LabLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(editable=False, max_length=20, unique=True)),
                ('shifts_per_day', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('hours_per_shift', models.DecimalField(decimal_places=2, default=8, max_digits=4)),
                ('include_saturday', models.BooleanField(default=False)),
                ('include_sunday', models.BooleanField(default=False)),
                ('base_capacity_per_hour', models.DecimalField(decimal_places=2, help_text='Units produced per hour at 100% efficiency', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('efficiency_factor', models.DecimalField(decimal_places=2, default=0.85, help_text='Production efficiency (0-1)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_lines', to='simulation.site')),
            ],
            options={
                'verbose_name': 'Lab Line',
                'verbose_name_plural': 'Lab Lines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LabProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(editable=False, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_products', to='simulation.productcategory')),
                ('default_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_products', to='simulation.productionline')),
                ('lab_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='simulation.labcategory')),
                ('lab_default_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_products', to='simulation.labline')),
            ],
            options={
                'verbose_name': 'Lab Product',
                'verbose_name_plural': 'Lab Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LabForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_demand', models.DecimalField(decimal_places=2, help_text='Total annual demand to distribute with seasonality', max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_forecasts', to='simulation.client')),
                ('lab_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='simulation.labclient')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_forecasts', to='simulation.product')),
                ('reference_product', models.ForeignKey(blank=True, help_text='Product to copy seasonality pattern from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_forecast_references', to='simulation.product')),
                ('lab_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='simulation.labproduct')),
            ],
            options={
                'verbose_name': 'Lab Forecast',
                'verbose_name_plural': 'Lab Forecasts',
                'ordering': ['-created_at'],
            },
        ),
    ]
