# Generated by Django 6.0 on 2026-01-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0007_add_lab_models'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['is_active'], name='simulation__is_acti_48eb86_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['code'], name='simulation__code_e1670a_idx'),
        ),
        migrations.AddIndex(
            model_name='lineconfigoverride',
            index=models.Index(fields=['is_active'], name='simulation__is_acti_845ec2_idx'),
        ),
        migrations.AddIndex(
            model_name='lineconfigoverride',
            index=models.Index(fields=['line', 'is_active'], name='simulation__line_id_897e21_idx'),
        ),
        migrations.AddIndex(
            model_name='lineproductassignment',
            index=models.Index(fields=['line', 'is_default'], name='simulation__line_id_dd944b_idx'),
        ),
        migrations.AddIndex(
            model_name='lineproductassignment',
            index=models.Index(fields=['product', 'is_default'], name='simulation__product_4a0744_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='simulation__is_acti_227a42_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='simulation__categor_69e9dd_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['default_line'], name='simulation__default_087e4b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['code'], name='simulation__code_bb146e_idx'),
        ),
        migrations.AddIndex(
            model_name='productionline',
            index=models.Index(fields=['is_active'], name='simulation__is_acti_323124_idx'),
        ),
        migrations.AddIndex(
            model_name='productionline',
            index=models.Index(fields=['site', 'is_active'], name='simulation__site_id_782193_idx'),
        ),
    ]
