# Generated by Django 6.0 on 2026-01-08 13:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0008_add_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomShiftConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('shifts_per_day', models.IntegerField(help_text='Number of shifts per day (1-4)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('hours_per_shift', models.DecimalField(decimal_places=2, help_text='Hours per shift', max_digits=4)),
                ('days_per_week', models.IntegerField(help_text='Number of working days (1-7)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('includes_saturday', models.BooleanField(default=False)),
                ('includes_sunday', models.BooleanField(default=False)),
                ('is_custom', models.BooleanField(default=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Custom Shift Configuration',
                'verbose_name_plural': 'Custom Shift Configurations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SimulationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('product_types', models.TextField(blank=True, default='', help_text='Comma-separated product types to include')),
                ('recipe_types', models.TextField(blank=True, default='', help_text='Comma-separated recipe types to include')),
                ('material_types', models.TextField(blank=True, default='', help_text='Comma-separated material types to include')),
                ('packaging_types', models.TextField(blank=True, default='', help_text='Comma-separated packaging types to include')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Simulation Category',
                'verbose_name_plural': 'Simulation Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='material_type',
            field=models.CharField(blank=True, default='', help_text='Material type classification', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='packaging_type',
            field=models.CharField(blank=True, default='', help_text='Packaging type classification', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, default='', help_text='Product type classification', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='recipe_type',
            field=models.CharField(blank=True, default='', help_text='Recipe type classification', max_length=100),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type'], name='simulation__product_6da57b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['recipe_type'], name='simulation__recipe__c03d92_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['material_type'], name='simulation__materia_baeade_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['packaging_type'], name='simulation__packagi_0af895_idx'),
        ),
        migrations.AddField(
            model_name='simulationcategory',
            name='lines',
            field=models.ManyToManyField(blank=True, help_text='Production lines included in this category', related_name='simulation_categories', to='simulation.productionline'),
        ),
        migrations.AddField(
            model_name='simulationcategory',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Filter lines by this site (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulation_categories', to='simulation.site'),
        ),
    ]
