# Generated by Django 6.0 on 2026-01-08 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0009_customshiftconfiguration_simulationcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineconfigoverride',
            name='days_per_week',
            field=models.IntegerField(default=5, help_text='Number of working days per week (0-7)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='lineconfigoverride',
            name='shifts_per_day',
            field=models.IntegerField(help_text='Number of shifts per day (0-4, 0 = shutdown)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
