# Generated by Django 6.0 on 2026-01-08 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0010_add_days_per_week_to_override'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labproduct',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['code']},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='simulation__categor_69e9dd_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
