# Generated by Django 6.0 on 2026-01-12 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0011_remove_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labproduct',
            name='lab_category',
        ),
        migrations.RemoveField(
            model_name='labforecast',
            name='lab_client',
        ),
        migrations.RemoveField(
            model_name='labforecast',
            name='client',
        ),
        migrations.RemoveField(
            model_name='labforecast',
            name='lab_product',
        ),
        migrations.RemoveField(
            model_name='labforecast',
            name='product',
        ),
        migrations.RemoveField(
            model_name='labforecast',
            name='reference_product',
        ),
        migrations.RemoveField(
            model_name='labline',
            name='site',
        ),
        migrations.RemoveField(
            model_name='labproduct',
            name='lab_default_line',
        ),
        migrations.RemoveField(
            model_name='labproduct',
            name='default_line',
        ),
        migrations.DeleteModel(
            name='LabCategory',
        ),
        migrations.DeleteModel(
            name='LabClient',
        ),
        migrations.DeleteModel(
            name='LabForecast',
        ),
        migrations.DeleteModel(
            name='LabLine',
        ),
        migrations.DeleteModel(
            name='LabProduct',
        ),
    ]
