# Generated by Django 6.0 on 2026-01-13 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0012_remove_labproduct_lab_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customshiftconfiguration',
            name='opening_cleaning_time',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Hours to subtract for opening/cleaning time', max_digits=4, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='customshiftconfiguration',
            name='saturday_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total hours worked on Saturday (if included)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AddField(
            model_name='customshiftconfiguration',
            name='sunday_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total hours worked on Sunday (if included)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AddField(
            model_name='lineconfigoverride',
            name='name',
            field=models.CharField(blank=True, help_text='Optional name for this override scenario (e.g., "Peak Season Config", "Maintenance Mode")', max_length=100),
        ),
        migrations.AddField(
            model_name='lineconfigoverride',
            name='opening_cleaning_time',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Hours to subtract for opening/cleaning time', max_digits=4, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='lineconfigoverride',
            name='saturday_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total hours worked on Saturday (if included)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AddField(
            model_name='lineconfigoverride',
            name='sunday_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total hours worked on Sunday (if included)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AddField(
            model_name='shiftconfiguration',
            name='opening_cleaning_time',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Hours to subtract for opening/cleaning time', max_digits=4, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='shiftconfiguration',
            name='saturday_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total hours worked on Saturday (if included)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AddField(
            model_name='shiftconfiguration',
            name='sunday_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total hours worked on Sunday (if included)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
    ]
